### ISSUE TITLE
Onglets Anticorps et Historique ne marchent plus

### ISSUE THREAD

**Issue by GevH2P2** [bgo-bioimagerie/docker-platformmanager#6]
Bonjour,
Plateforme H2P2 à Rennes. Je vous contacte car on a plus accès à l'onglet Anticorps et Historique sur Plateforme Manager.

J'ai le message: Error:
Unknown named parameter $letter

Pouvez vous régler ce problème en urgence svp.  

Cordialement

**Comment by osallou** [comment]
Pouvez vous donner l url de chacun?

**Comment by osallou** [comment]
mauvais repo, je créé l'issue https://github.com/bgo-bioimagerie/platformmanager/issues/258

**Comment by osallou** [comment]
@GevH2P2 normalement c'est corrigé

**Comment by GevH2P2** [comment]
Bonjour,
Merci ça remarche. Merci beaucoup !
J'ai juste un autre problème plus subtile. Quand je vais dans l'onglet Anticorps, je cherche par nom, j'ai plusieurs résultats.https://pfm.genouest.org/anticorpsadvsearchquery/8
 Je clique un pour visualiser un, je fais marche arrière j'ai un erreur. Voici le message : 

Confirmer le nouvel envoi du formulairePour s'afficher correctement, cette page Web a besoin des données que vous avez saisies précédemment. Vous pouvez envoyer de nouveau ces données. Cependant, en procédant ainsi, vous répéterez toute action déjà effectuée sur cette page.
Veuillez appuyer sur le bouton d'actualisation pour renvoyer les données nécessaires au chargement de la page.
ERR_CACHE_MISS

**Comment by GevH2P2** [comment]
J'ai testé le lien, il ne marche pas. Quand je vais sur l'onglet anticorps, je cherche tout les Ac qui commence par Caspas ou autre nom, du moment que j'ai plusieurs résultats, je clique sur un des résultats, je visualise, je clique sur marche arrière pour revoir les résultats avec caspas et j'ai le message d'erreur : 

Confirmer le nouvel envoi du formulairePour s'afficher correctement, cette page Web a besoin des données que vous avez saisies précédemment. Vous pouvez envoyer de nouveau ces données. Cependant, en procédant ainsi, vous répéterez toute action déjà effectuée sur cette page.
Veuillez appuyer sur le bouton d'actualisation pour renvoyer les données nécessaires au chargement de la page.
ERR_CACHE_MISS

**Comment by osallou** [comment]
les "marches arrières" selon les pages vont renvoyer des formulaires, c"était déjà le cas "avant" et c'est une mauvais pratique ds ce cas. Cela peut se faire mais avoir de effets de bord. 

par ailleurs vous etes ds le mauvais répo (cf commentaire plus haut).

Comme il s'agit d'autres pb, merci de les créer ds:

https://github.com/bgo-bioimagerie/platformmanager/issues

et de ne pas mélanger pls pbs ds une meme issue

**Comment by osallou** [comment]
plutot qu'un retour arrière, vous pouvez simplement recliquer sur le menu attendu

**Comment by GevH2P2** [comment]
Oui ça marche si je reclique sur anticorps il me remets sur le résultat de recherche mais pas en marche arrière. Ok je vais faire attention à ça. Merci pour les solution apporté et vos conseilles :) . Bonne journée !

Cordialement

**Comment by osallou** [comment]
pour info, cette semaine l'équipe de dev est en congés, donc faibles voir pas de dispos...

**Comment by osallou** [comment]
Note for dev:

The *search* sends a POST with search params to display result list. Clicking on navigator *back* button will expect to resubmit form params (which is fine and can be confirmed by user) but depending on back resubmiting can have side effects.

Correct behavior is clicking on menu to go back to search list and not going to previous history.

Possible workaround would be to send the POST then to redirect to a GET with result page, but adds complexity
